# Generated by Django 5.2.12 on 2026-03-07 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='diseaseinfo',
            options={'ordering': ['name'], 'verbose_name': 'Disease Info', 'verbose_name_plural': 'Disease Infos'},
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='severity',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='mild', max_length=20),
        ),
        migrations.AddField(
            model_name='diseaseinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Comma-separated symptoms', null=True),
        ),
        migrations.AlterField(
            model_name='diseaseinfo',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
